# Site settings
title: Eithan Shavit
email: eithanshavit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sharing my personal projects, thoughts and ideas
baseurl: ""
url: "http://eithanshavit.com"
github_username:  eithanshavit

# Build settings
markdown: kramdown

# Ignore
exclude:
- "bower_components"
- "bower.json"
- "Gruntfile.coffee"
- "node_modules"
- "package.json"
